server:
  port: 19090
  servlet:
    session:
      timeout: 1800
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    driverClassName: org.postgresql.Driver
    url: ENC(AUDZhPAjbhCk2PHnOlMa6qqU1gZ+HvTgD01b3FDNw8naC1jvCG4n27KFraUYwClcQ9I2vpLAiFRbTDFXHBqJ4ZnHo22iUf6qPo2u/DgKsW1/tO3sFKlQlVbSkVn4wY//zVwmaO+hdLM=)
    username: ENC(p/64CiyEW+mqrz+ks6rekA==)
    password: ENC(nF8qVW4Au/T0NilfKEeU18P16jqhM0Pt)
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(NMdFhxRQN1N5ghGpK4NKzvenrdXn1jmZW9klHsk9YMU=)
    password: ENC(cmzS0QLO09Jy0MMwRdL2Hf3NWlB4+J7KC3FsQtZXhUM=)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
global:
  url:
    admin: "http://localhost:19090"
    user: "http://localhost"
  file:
    savePath: "/home/ec2-user/project/uploadFiles/admin/"
    webPath: "/uploadFiles/admin/"
    max-size: 10 #MB
    ext: "jpg,jpeg,gif,bmp,png,zip"
  mail:
    templates:
      path: "/templates/mail/"

jasypt:
  key: ${jasypt_key}